language: python
sudo: true

python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - env
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl

install:
  - pip install .
  - pip install -U pytest
  - pip install -r requirements.txt

before_script:
  - wget https://launchpad.net/test-db/employees-db-1/1.0.6/+download/employees_db-full-1.0.6.tar.bz2
  - bunzip2 employees_db-full-1.0.6.tar.bz2
  - tar -xvf employees_db-full-1.0.6.tar
  - cd employees_db
  - mysql -t < employees.sql

# command to run tests
script: py.test -v tests